image:
  file: Dockerfile
# Command to start on workspace startup (optional)
tasks:
  - command: pip3 install ocrmypdf
  - command: echo "source /workspace/bash-completion/completions/ocrmypdf " >> ~/.bashrc
